### ISSUE TITLE
logo appears with tint 

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/web-design-2-independent-project#15]
Hi @thatkidmadrid

My logo keeps showing up with a tint in the background even when I saved it for transparency and when I open the png it's transparent. Do you know why this is happening?

**Comment by thatkidmadrid** [comment]
Target the image in your css and give it `background: none` or even better `background-color: rgba(150,110,100, 0)` (i just pulled a brown from your site, but it can be any rgba colour you want with the alpha set to 0) This is better because you can then give it a hover/focus state that will put back a background and make that state more obvious!

**Comment by askaalyy** [comment]
Thank you it worked!
